### ISSUE TITLE
Is time series classification supported?

### ISSUE THREAD

**Issue by jagandecapri** [PlasmaControl/PyRCN#38]
Hi,

Given I have a time-series data with `X_train shape = (samples, sequences, features)` and a binary `y_train shape = (samples,)`, how can I fit and predict using pyRCN ESNClassifier?

For example, if I generate the following variables

```
X_train = np.arange(27).reshape(3,3,3)
y_train = np.random.randint(0,2,3) # assume it generates [1,1,0]

X_test = X_train
```

When I call `predict(X=X_test)`, it should be returning `[1,1,0]`. So far as I understand from the codebase, pyRCN only takes X as shape `(n_samples, n_features)` for the `fit` and `predict` functions.

On a side note, I am not sure whether the question I raised is similar to https://github.com/TUD-STKS/PyRCN/issues/12.

**Comment by renierts** [comment]
Hi @jagandecapri,

I see. In that case, I have understood it wrong in your original example. However, as you say it, the user just would need to transpose the dimensions.

I will allow 3D numpy arrays as ```(time_sequence, samples, features)``` and internally convert it as explained in my example. 

The idea behind my current solution is that I want to deal with arbitrary sequence lengths. Using 3D numpy arrays ```(time_sequence, samples, features)```, this is only possible by zeropadding all sequences to the same length.

Can you work with the workaround I proposed in my first comment for now?

**Comment by jagandecapri** [comment]
Hi @renierts,

Working with a toy example as code below, I find that the prediction array is shorter than my expectation. Any idea why?

```
BATCH_LENGTH = 3
SEQUENCE_LENGTH = 2
FEATURES = 3

BATCH_IDX = 0
SEQUENCE_IDX = 1
FEATURE_IDX = 2

time_series_input = np.arange(18).reshape(BATCH_LENGTH,SEQUENCE_LENGTH,FEATURES)

# Transpose from (BATCH, SEQUENCE, FEATURE) to (SEQUENCE, BATCH, FEATURE)
time_series_input_T = np.transpose(time_series_input, (SEQUENCE_IDX,BATCH_IDX,FEATURE_IDX))

# Generate time series label equivalent to BATCH_LENGTH
time_series_label = np.random.randint(0,2,BATCH_LENGTH)

# Convert to dtype=object
X_train = np.empty(shape=(SEQUENCE_LENGTH, ), dtype=object)
for i, x in enumerate(time_series_input_T):
    X_train[i] = x

# Expand dim of labels
y_train = np.expand_dims(time_series_label, axis=1)
print(f'y_train: {y_train}')

X_test = X_train
esn = SeqToLabelESNClassifier().fit(X_train, y_train)

# Prediction array length is only 2. It should be 3, I suppose?
print(f'y_pred: {esn.predict(X_test)}')
```

**Comment by renierts** [comment]
Hi @jagandecapri,
I think I misunderstood you at first. Sorry therefore. Some questions:
- ```BATCH_LENGTH = 3```: Do you have three sequences?
- ```SEQUENCE_LENGTH = 2```: Do you have a sequence length of 2?

If this is true, the solution is that ```X_train = np.empty(shape=(BATCH_LENGTH, ), dtype=object)```. The following code snippet should work:

```
import numpy as np
from pyrcn.echo_state_network import SeqToLabelESNClassifier


BATCH_LENGTH = 3
SEQUENCE_LENGTH = 2
FEATURES = 3

BATCH_IDX = 0
SEQUENCE_IDX = 1
FEATURE_IDX = 2

time_series_input = np.arange(18).reshape(BATCH_LENGTH,SEQUENCE_LENGTH,FEATURES)

# Generate time series label equivalent to BATCH_LENGTH
time_series_label = np.random.randint(0,2,BATCH_LENGTH)

# Convert to dtype=object
X_train = np.empty(shape=(BATCH_LENGTH, ), dtype=object)

for i, x in enumerate(time_series_input):
    # Each element of X_train has the shape (SEQUENCE_LENGTH, FEATURES)
    X_train[i] = x

# Expand dim of labels
y_train = np.expand_dims(time_series_label, axis=1)
print(f'y_train: {y_train}')

X_test = X_train
esn = SeqToLabelESNClassifier().fit(X_train, y_train)

# Prediction array length is only 2. It should be 3, I suppose?
print(f'y_pred: {esn.predict(X_test)}')
```

**Comment by renierts** [comment]
That's what I understood too. You have ```BATCH_LENGTH``` recordings, where each recording has a duration of ```SEQUENCE_LENGTH``` and where each recording has ```FEATURE_LENGTH``` features.
